---
# Prospector configuration
# See https://prospector.landscape.io/en/master/usage.html

vulture:
  run: false

bandit:
  run: false

pyright:
  run: true

ruff:
  run: true

# Disable mccabe complexity warnings
mccabe:
  run: false

# Configure pylint
pylint:
  options:
    ignored-modules:
      - git
