# Prospector configuration
# See https://prospector.landscape.io/en/master/usage.html

# Disable mccabe complexity warnings
mccabe:
  run: false

# Configure pylint
pylint:
  options:
    ignored-modules:
      - git
